### ISSUE TITLE
Doesn't just alphabetize

### ISSUE THREAD

**Issue by mapsiter** [mattkenefick/vscode-css-alphabetize#1]
Hi, I wish it wouldn't do anything else but alphabetize between curly braces but it also puts empty lines between selectors, so for example:

.b-faq {
  .c-section-header {
    &__title {
      font-size: 3.2rem;
      background-color: $color-white;
    }
  }

  &__item-title {
    font-size: 1.8rem;
    background-color: #fff;
  }
}

becomes:

.b-faq {
  
  .c-section-header {
    
    &__title {
      background-color: $color-white;
      font-size: 3.2rem;
    }
  }

  &__item-title {
    background-color: #fff;
    font-size: 1.8rem;
  }
}

Nicely did the alphabetizing but triggers unwanted Stylelint errors. Is there an option to make it not doing anything else?
Cheers

**Comment by mattkenefick** [comment]
Ack. I'll have a look.

**Comment by mattkenefick** [comment]
Should be resolved in 0.3.0
